server:
  port: 8080

spring:
  application:
    name: cb-user-service

aws:
  region: ${AWS_REGION:us-east-1}
  dynamodb:
    table-name: ${DYNAMODB_TABLE_NAME:cb-user-service-dev-users}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
